name: Homebrew Bump Formula
on:
  release:
    types: [published]
jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formula: driftctl
